version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - .:/code
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    command: sh -c "gunicorn mysite.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
