version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    env_file:
      - ./.env
    #command: python /code/manage.py runserver 0.0.0.0:8000
    #python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt &&
    command: sh -c "export ALLOWED_HOSTS=$34.223.4.188
                    export ALLOWED_CLIENT_HOSTS=$34.223.4.188
                    export DEBUG=True
                    export SECRET_KEY=123456
                    export INTERNAL_34.223.4.188S=127.0.0.1,$34.223.4.188,
                    export API_URI=http://$34.223.4.188:8000/graphql/
                    export APP_MOUNT_URI=/dashboard/
                    export DEFAULT_COUNTRY=IN
                    export DEFAULT_CURRENCY=INR
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000 &&
                    python manage.py collectstatic --noinput &&
                    python manage.py dumpdata > db_old.json &&
                    gunicorn saleor.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  static_volume:
  media_volume:
