version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:  # <-- wait for web to be "ready" before starting this service
      - web
    networks:  # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge