version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/opt/services/app/static  # <-- bind the static volume
      - media_volume:/opt/services/app/media  # <-- bind the media volume
    ports:
      - 8000:8000
      
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/app/static  # <-- bind the static volume
      - media_volume:/opt/services/app/media  # <-- bind the media volume

    depends_on:  # <-- wait for web to be "ready" before starting this service
      - web
    networks:  # <-- here
      - nginx_network
      
  database1:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:10
    env_file:  # <-- we use the previously defined values
      - config/db/database1_env
    networks:  # <-- connect to the bridge
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge

volumes:
  database1_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
